# Generated by Django 5.2.11 on 2026-02-27 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _populate_category_slugs(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _normalize_orders(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_lecture_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
    ]


def _populate_category_slugs(apps):
    Category = apps.get_model('courses', 'Category')
    existing = set(
        Category.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True)
    )
    for cat in Category.objects.all().only('id', 'name', 'slug'):
        if cat.slug and cat.slug.strip():
            continue
        base = slugify(cat.name) or "category"
        candidate = base
        if candidate in existing:
            candidate = f"{base}-{cat.id}"
        # ensure unique even if base-id collides
        i = 2
        while candidate in existing:
            candidate = f"{base}-{cat.id}-{i}"
            i += 1
        cat.slug = candidate
        cat.save(update_fields=['slug'])
        existing.add(candidate)


def _normalize_orders(apps):
    Module = apps.get_model('courses', 'Module')
    Lecture = apps.get_model('courses', 'Lecture')

    # Ensure module.order is unique per course
    for course_id in Module.objects.values_list('course_id', flat=True).distinct():
        modules = list(Module.objects.filter(course_id=course_id).order_by('id'))
        for idx, m in enumerate(modules, start=1):
            if m.order != idx:
                m.order = idx
                m.save(update_fields=['order'])

    # Ensure lecture.order is unique per module
    for module_id in Lecture.objects.values_list('module_id', flat=True).distinct():
        lectures = list(Lecture.objects.filter(module_id=module_id).order_by('id'))
        for idx, l in enumerate(lectures, start=1):
            if l.order != idx:
                l.order = idx
                l.save(update_fields=['order'])
